# ==================
# MONITOR CONFIG
# ==================
# monitor = eDP-2, 2560x1600@239.998993, 2560x0, 1, vrr, 1
monitor = , preferred,auto,auto

# --- Toolkit Backend Environment Variables ---
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = _JAVA_AWT_WM_NONREPARENTING,1
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

# ==================
# INPUT CONFIG
# ==================
input {
    kb_layout = us
    numlock_by_default = true
    accel_profile = flat

    touchpad {
        natural_scroll = yes
      }
}

gesture = 3, horizontal, workspace
gesture = 3, swipe, mod: SUPER, resize

# ==================
# MISC
# ==================
misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    vrr = 1
    middle_click_paste = false
}

source = ./modules/autostart.conf
source = ./modules/binds.conf
source = ./modules/colors.conf
source = ./modules/cursor.conf
source = ./modules/layout.conf
source = ./modules/windowrules.conf
