# ==================
# CURSOR CONFIG
# ==================

env = HYPRCURSOR_THEME,Bibata-Modern-Classic
env = XCURSOR_THEME,Bibata-Modern-Classic
env = HYPRCURSOR_SIZE,24
env = XCURSOR_SIZE,24

cursor {
    inactive_timeout = 10
    no_hardware_cursors = 0
    no_warps = true
}
